

export default function TermsPage() {
    return (
        <div className="flex flex-col min-h-screen bg-background">

            <main className="flex-1 py-12 md:py-20">
                <div className="container mx-auto px-4 max-w-4xl">
                    <h1 className="font-headline text-3xl md:text-4xl font-bold tracking-tighter mb-8">
                        Terms of Service
                    </h1>
                    <div className="prose prose-invert max-w-none text-muted-foreground">
                        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">1. Acceptance of Terms</h2>
                        <p className="mb-4">
                            By accessing and using Echo: The Bridge, you accept and agree to be bound by the terms and provision of this agreement. In addition, when using this websites particular services, you shall be subject to any posted guidelines or rules applicable to such services.
                        </p>

                        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">2. Description of Service</h2>
                        <p className="mb-4">
                            Echo: The Bridge provides users with AI-generated strategic roadmaps based on user input. You understand and agree that the Service is provided "AS-IS" and that Echo: The Bridge assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.
                        </p>

                        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">3. Registration</h2>
                        <p className="mb-4">
                            You verify that any contact information you provide is true and accurate. You agree to keep your password confidential and will be responsible for all use of your account and password.
                        </p>

                        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">4. AI Output Disclaimer</h2>
                        <p className="mb-4">
                            The content generated by our AI is for informational and educational purposes only. It does not constitute professional advice (medical, legal, financial, etc.). You should not rely solely on the generated roadmaps for critical life decisions without using your own judgment and consulting appropriate professionals.
                        </p>

                        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">5. Intellectual Property</h2>
                        <p className="mb-4">
                            You retain rights to the text descriptions you input. Echo: The Bridge claims no ownership over your personal goals. However, the underlying software, design, and AI workflows are the property of Echo: The Bridge.
                        </p>

                        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">6. Termination</h2>
                        <p className="mb-4">
                            We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                        </p>

                        <p className="mt-12 text-sm italic">
                            Last updated: January 14, 2026
                        </p>
                    </div>
                </div>
            </main>
        </div>
    );
}
